config/routes.rb
Rails.application.routes.draw do
  root 'users#new'
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show, :edit, :update] do
    get :favorites, on: :collection
    get :confirm, on: :collection
  end
  resources :blogs do
    collection do
      post :confirm
    end
  end
  resources :favorites, only: [:index, :create, :destroy]
  mount LetterOpenerWeb::Engine, at: "/letter_opener"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  validates :content, presence: true, length: { in: 1..140 }
  belongs_to :user
  mount_uploader :image, ImageUploader
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :blog
end

app/models/post.rb
class Post < ApplicationRecord
  validates :content, presence: true, length: { in: 1..140 }
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :blogs
  has_many :favorites, dependent: :destroy

  mount_uploader :image, ImageUploader

  before_validation { email.downcase! }

  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 }, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }, uniqueness: true

  has_secure_password
  validates :password, length: { minimum: 6 }, on: :new

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  before_action :login_required

  private

  def login_required
    redirect_to new_session_path unless current_user
  end

  def fobid_login_user
    if @current_user
      flash[:notice]="ログインしています"
      redirect_to("/blogs/index")
    end
  end

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  def index
    @blogs = Blog.all
  end

  def new
    @blog = Blog.new
  end

  def create
    @blog = Blog.new(blog_params)
    @blog = current_user.blogs.build(blog_params)
      if params[:back]
        render :new
      else
        if @blog.save
          BlogMailer.blog_mail(@blog).deliver
          redirect_to blogs_path, notice: "ブログ作成完了！"
        else
          render :new
        end
      end
  end

  def confirm
    @blog = current_user.blogs.build(blog_params)
    render :new if @blog.invalid?
  end

  def show
    @favorite = current_user.favorites.find_by(blog_id: @blog.id)
  end

  def edit
    if @blog.user == current_user
      render "edit"
    else
      redirect_to blogs_path
    end
  end

  def update
    if @blog.update(blog_params)
      redirect_to blogs_path, notice: "ブログ編集完了！"
    else
      render :edit
    end
  end

  def destroy
    @blog.destroy
    redirect_to blogs_path, notice: "ブログ削除完了！"
  end

  private

  def blog_params
    params.require(:blog).permit(:title, :content, :user_id, :image, :image_cache)
  end

  def set_blog
    @blog = Blog.find(params[:id])
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def index
    @favorites = current_user.favorites
  end

  def create
    favorite = current_user.favorites.create(blog_id: params[:blog_id])
    redirect_to blogs_path, notice: "#{favorite.blog.user.name}さんのブログをお気に入り登録しました"
  end

  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to blogs_path, notice: "#{favorite.blog.user.name}さんのブログをお気に入り解除しました"
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  def index
    @blogs = Blog.all
  end

  def new
    @blog = Blog.new
  end

  def create
    @blog = Blog.new(blog_params)
    @blog = current_user.blogs.build(blog_params)
      if params[:back]
        render :new
      else
        if @blog.save
          redirect_to blogs_path, notice: "ブログ作成完了！"
        else
          render :new
        end
      end
  end

  def confirm
    @blog = current_user.blogs.build(blog_params)
    render :new if @blog.invalid?
  end

  def show
  end

  def edit
  end

  def update
    if @blog.update(blog_params)
      redirect_to blogs_path, notice: "ブログ編集完了！"
    else
      render :edit
    end
  end

  def destroy
    @blog.destroy
    redirect_to blogs_path, notice: "ブログ削除完了！"
  end

  private

  def blog_params
    params.require(:blog).permit(:title, :content, :user_id, :image, :image_cache)
  end

  def set_blog
    @blog = Blog.find(params[:id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render "edit"
    else
      redirect_to user_path
    end
  end

  def confirm
    @user = current_user.blogs.build(user_params)
    render :show if @user.invalid?
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path, notice: "プロフィール画像編集完了！"
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation,:image, :image_cache)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'create'
      confirm_blogs_path
    elsif action_name == 'edit'
      blog_path
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'create'
      confirm_blogs_path
    elsif action_name == 'edit'
      blog_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model:@blog, local: true , url: choose_new_or_edit) do |form|%>
  <% if @blog.errors.any?%>
  <div id="error_explanation">
    <h2><%=@blog.errors.count %>件のエラーがあります</h2>
    <ul>
    <% @blog.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
  <% end%>

  <div class="blog_content">
    <%= form.label :content%>
    <%= form.text_field :content%>
  </div>
  <div class="image_field">
    <%= form.label :image %>
    <%= image_tag(@blog.image.url) if @blog.image && @blog.image.url %>
    <%= form.file_field :image %>
    <%= form.hidden_field :image_cache %>
  </div>
    <%= form.submit "送信"%>
<% end %>

<%= link_to "戻る", blogs_path%>

app/views/blogs/confirm.html.erb
<h3>以下の内容で、送信する。</h3>
<%= form_with(model: @blog, local: true) do |form| %>
  <%= form.hidden_field :content %>
  <%= form.hidden_field :image_cache %>
  <p>本文:<%= @blog.content %></p>
  <%= image_tag(@blog.image.url) if @blog.image && @blog.image.url %>
  <%= form.submit  "登録する" %>
  <%= form.submit "戻る", name: 'back'%>
<% end %>

<%= form_with(model:@blog, url:new_blog_path, local:true, method:"get") do |form| %>
  <%= form.hidden_field :content %>
  <%= form.hidden_field :image_cache %>
  <%= form.submit "戻る", name: "back" %>
<% end %>

app/views/blogs/edit.html.erb
<h1>編集画面</h1>
<%= render 'form'%>

app/views/blogs/index.html.erb
<h1>投稿一覧</h1>
<%= link_to "Create New", new_blog_path, class:"btn" %>
<%= link_to "Mail", 'http://localhost:3000/letter_opener'%>
<table>
  <tr>
    <th>名前</th>
    <th>内容</th>
    <th></th>
    <th></th>
  </tr>
  <% @blogs.each do |blog| %>
    <tr>
      <td><%= blog.user.name %></td>
      <td><%= blog.content %></td>
      <td><%= image_tag(blog.image.url) if blog.image && blog.image.url %></td>
      <td><%= link_to "詳細画面へ", blog_path(blog.id) %></td>
      <td>
        <% if blog.user_id == current_user.id %>
          <%= link_to "編集画面へ", edit_blog_path(blog.id), data:{confirm:'本当に編集してよいですか？'}%>
        <% end %>
      </td>
      <td>
        <% if blog.user_id == current_user.id %>
          <%= link_to "削除する",blog_path(blog.id),method: :delete, data:{confirm:'本当に削除してよいですか？'}%></td>
        <% end %>
    </tr>
  <% end %>
</table>

app/views/blogs/new.html.erb
<h1>新規作成画面</h1>
<%= render 'form' %>

app/views/blogs/show.html.erb
<h1>詳細画面</h1>
<p>名前:<%= @blog.user.name %></p>
<p>内容<%= @blog.content %></p>
<p>
  <strong>Image:</strong>
  <%= image_tag @blog.image.url, style: 'width:70px;height:70px' %>
</p>
<% unless @blog.user_id == current_user.id %>
  <% if @favorite.present? %>
    <%= link_to 'お気に入り解除する', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
  <% else %>
    <%= link_to 'お気に入りする', favorites_path(blog_id: @blog.id), method: :post, class: 'btn btn-primary' %>
  <% end %>
<% end %>
<%= link_to 'ブログ一覧へ', blogs_path%>

app/views/favorites/index.html.erb
<h1>お気に入り一覧</h1>
<%= link_to "Back", user_path(current_user.id), class:"btn" %>
<table>
  <tr>
    <th>名前</th>
    <th>内容</th>
  </tr>
  <% @favorites.each do |favorite| %>
    <tr>
      <td><%= favorite.blog.user.name %></td>
      <td><%= favorite.blog.content %></td>
      <td><%= image_tag favorite.blog.image.url %></td>
    </tr>
  <% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PictApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>

    <% if logged_in? %>
    <%= link_to "Profile", user_path(current_user.id), class:"btn" %>
    <%= link_to "Logout", session_path(current_user.id), method: :delete, class:"btn" %>
    <% else %>
    <%= link_to "Sign up", new_user_path, class:"btn" %>
    <%= link_to "Login", new_session_path, class:"btn" %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model:@blog, local: true , url: choose_new_or_edit) do |form|%>
<% if @blog.errors.any?%>
<div id="error_explanation">
  <h2><%=@blog.errors.count %>件のエラーがあります</h2>
  <ul>
  <% @blog.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
  </ul>
</div>
<% end%>

  <div class="blog_content">
    <%= form.label :content%>
    <%= form.text_field :content%>
  </div>
  <div class="image_field">
    <%= form.label :image %>
    <%= image_tag(@blog.image.url) if @blog.image && @blog.image.url %>
    <%= form.file_field :image %>
    <%= form.hidden_field :image_cache %>
  </div>
    <%= form.submit "送信"%>

<% end %>

<%= link_to "戻る", blogs_path%>

app/views/posts/confirm.html.erb
<h3>以下の内容で、送信する。</h3>
<%= form_with(model: @blog, local: true) do |form| %>
  <%= form.hidden_field :content %>
  <%= form.hidden_field :image_cache %>
  <p>本文:<%= @blog.content %></p>
  <%= image_tag(@blog.image.url) if @blog.image && @blog.image.url %>
  <%= form.submit  "登録する" %>
  <%= form.submit "戻る", name: 'back'%>
<% end %>

app/views/posts/edit.html.erb
<h1>編集画面</h1>
<%= render 'form'%>

app/views/posts/index.html.erb
<h1>投稿一覧</h1>
<%= link_to "新規作成画面へ", new_blog_path, class:"btn" %>
<table>
  <tr>
    <th>名前</th>
    <th>内容</th>
    <th></th>
    <th></th>
  </tr>
  <% @blogs.each do |blog| %>
  <tr>
    <td><%= blog.user.name %></td>
    <td><%= blog.content %></td>
    <td><%= image_tag(blog.image.url) if blog.image && blog.image.url %></td>
    <td><%= link_to "詳細画面へ", blog_path(blog.id) %></td>
    <td><%= link_to "編集画面へ", edit_blog_path(blog.id), data:{confirm:'本当に編集してよいですか？'}%></td>
    <td><%= link_to "削除する",blog_path(blog.id),method: :delete, data:{confirm:'本当に削除してよいですか？'}%></td>
  </tr>
  <% end %>
</table>

app/views/posts/new.html.erb
<h1>新規作成画面</h1>
<%= render 'form' %>

app/views/posts/show.html.erb
<h1>詳細画面</h1>
<p>名前:<%= @blog.user.name %></p>
<p>内容<%= @blog.content %></p>
<p>
  <strong>Image:</strong>
  <%= image_tag @blog.image.url %>
</p>
<%= link_to 'ブログ一覧へ', blogs_path%>

app/views/users/confirm.html.erb
<h1>確認画面</h1>
<%= form_with(model:@user, url:new_user_path, local:true, method:"get") do |form| %>
  <%= image_tag(@user.image.url) if @user.image && @user.image.url %>
  <%= form.hidden_field :image_cache %>
  <%= form.submit "戻る", name: "back" %>
<% end %>

app/views/users/edit.html.erb
<h1>編集画面</h1>
<%= form_with(model: @user, local: true) do |form| %>
<div class="user_name">
  <%= form.label :name%>
  <%= form.text_field :name%>
</div>

  <div class="user_email">
    <%= form.label :email%>
    <%= form.text_field :email%>
  </div>

  <div class="image_field">
    <%= form.label :image %>
    <%= form.file_field :image %>
    <%= form.hidden_field :image_cache %>
  </div>
  <%= form.submit "送信"%>
<% end %>
<%= link_to "Back", user_path(current_user.id), class:"btn btn_back" %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @user, local: true) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit "Create my account" %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %>さんのページ</h1>

<p>メールアドレス: <%= @user.email %></p>

<div>
  <% if @user.image? %>
    <%= image_tag @user.image.url %>
  <% else %>
    <%= image_tag 'user.icon.png', size: "150x150" %>
  <% end %>
</div>

<div class="btn_user">
<%= link_to "Edit Profile", edit_user_path(@user.id), data:{confirm:'本当に編集してよいですか？'}, class:"btn" %>
<%= link_to "Favorite list", favorites_path, class:"btn" %>
<%= link_to "Blog list", blogs_path, class:"btn" %>
</div>